Repository mutsatopia/guten-tag, pull requests merged in 2021-12, with the labels that each got.

#17 메인 보드 태그 렌더
  board.html
  css/boardStyle.css
  js/renderTags.js
Labels: enhancement

#20 js 파일 const 카멜케이스로 변경했습니다
  board.html
  css/boardStyle.css
  js/renderTags.js
  js/searchFilter.js
Labels: enhancement

#24 ✨ add html to index page
  index.html
Labels: enhancement

#26 index 페이지 css 추가
  css/indexStyle.css
  index.html
  resource/logoblack.png
  resource/logocolor.png
Labels: enhancement

#31 tagData 모듈화 및 tagdata 추가
  board.html
  js/data.js
  js/index.js
  js/renderTags.js
Labels: enhancement

#35 컨벤션, 오타 수정 및 보드 헤더 개선
  board.html
  css/boardStyle.css
  js/renderTags.js
  js/searchFilter.js
Labels: enhancement

#37 태그 선택시 border 색상 변경
  board.html
  css/boardStyle.css
  js/selectTags.js
Labels: enhancement

#44 placeholder 추가 및 코드 개선
  board.html
  css/boardStyle.css
  css/indexStyle.css
Labels: enhancement

#47 ready 태그 취소 기능 추가 및 커서 모양 변경
  board.html
  css/boardStyle.css
  js/board.js
  js/cursor.js
  js/grid.js
  js/renderTags.js
  js/selectTags.js
  js/tag.js
  resource/cursor.svg
Labels: enhancement

#55 attr 추가 기능 및 기타 css
  board.html
  css/boardStyle.css
  js/attrAdd.js
Labels: enhancement

#58 attrAdd.js 수정 및 data.js attr 삭제
  js/attrAdd.js
  js/data.js
Labels: enhancement

#62 스크롤 영역 수정 및 스크롤바 보이기
  css/boardStyle.css
Labels: enhancement

#63 어트리뷰트 창 UI 개선
  board.html
  css/boardStyle.css
  resource/dash-circle.svg
  resource/dash-circle_hover.svg
  resource/plus-circle.svg
  resource/plus-circle_hover.svg
Labels: enhancement

#66 attr 제거 기능 추가
  board.html
  css/boardStyle.css
  js/attrCustom.js
Labels: enhancement

#72 테마 기능 추가
  js/data.js
  js/renderTags.js
Labels: enhancement

#74 새 어트리뷰트 추가 및 취소 기능
  board.html
  css/boardStyle.css
  js/attrBtn.js
  js/attrCustom.js
Labels: enhancement

#78 어트리뷰트 추가 보완
  board.html
  css/boardStyle.css
  resource/plus-circle.svg
  resource/plus-circle_hover.svg
Labels: enhancement

#79 인덱스 페이지 내용 추가
  css/indexStyle.css
  index.html
  resource/boxes.svg
  resource/code-square.svg
  resource/columns.svg
  resource/display.svg
Labels: documentation

#81 드래그 기능 추가
  css/boardStyle.css
  js/board.js
  js/tag.js
Labels: enhancement

#82 어트리뷰트 내용 변경 및 삭제기능 버그 수정
  js/attrCustom.js
  js/board.js
Labels: bug
