Repository mutsatopia/guten-tag, pull requests merged in 2022-01, with the labels that each got.

#87 attr 창 input 버그 수정 및 코드 리팩토링
  css/boardStyle.css
  js/attrCustom.js
  js/board.js
Labels: bug

#89 코드 추출 모달창 생성
  board.html
  css/boardStyle.css
  css/font.css
  js/modal.js
  resource/x-lg.svg
Labels: enhancement

#90 추출 기능 추가
  css/boardStyle.css
  js/modal.js
Labels: enhancement

#91 어트리뷰트 편집 바와 태그 객체 연결 및 추출 기능 수정
  js/attrCustom.js
  js/board.js
  js/modal.js
  js/tag.js
Labels: bug, enhancement

#93 들여쓰기 선택 input 추가
  board.html
  css/boardStyle.css
  js/modal.js
Labels: enhancement

#95 board 격자 제거 check 기능 추가 및 css 변경 #94
  board.html
  css/boardStyle.css
  js/board.js
  js/grid.js
Labels: enhancement

#98 추출 코드 들여쓰기 바꾸기 기능
  board.html
  js/modal.js
Labels: enhancement

#100 코드 추출 모달창 UI 개선
  css/boardStyle.css
  js/modal.js
Labels: enhancement

#102 태그 데이터 업데이트
  js/data.js
Labels: documentation

#101 테마 수정
  css/boardStyle.css
  js/board.js
  js/data.js
  js/menuOpen.js
  js/renderTags.js
  js/tag.js
Labels: bug, enhancement

#107 attr창 UX 개선 css 변경
  css/boardStyle.css
  js/aside.js
  js/board.js
Labels: bug

#109 보드 UI 개선
  css/boardStyle.css
  js/attrBtn.js
  js/board.js
  js/renderTags.js
  js/tag.js
Labels: bug, enhancement

#112 보드 태그 데이터 삭제시 태그선택으로 변경
  js/board.js
Labels: enhancement

#113 격자 사이즈 변경 기능 추가
  js/board.js
  js/grid.js
  js/tag.js
Labels: enhancement

#115 리드미 작성
  README.md
  resource/planning1.png
  resource/planning2.png
Labels: documentation

#116 :sparkles: Add tag scale function
  js/board.js
Labels: enhancement

#118 태그 테두리 색상 수정
  css/boardStyle.css
  js/board.js
  js/tag.js
Labels: enhancement

#121 태그 크기 변경시 커서 모양 변경
  css/boardStyle.css
  js/board.js
  js/cursor.js
  resource/arrow.svg
Labels: enhancement

#122 구텐탁 서비스로 만든 구조 예시 추가
  README.md
  resource/example_structure.png
  resource/gutentag_structure.png
Labels: documentation
